export enum NOTIFICATION_EVENT {
  LEAD_CREATED = 'LEAD_CREATED',
  LEAD_ASSIGNED = 'LEAD_ASSIGNED',
  LEAD_STATUS_CHANGED = 'LEAD_STATUS_CHANGED',

  TASK_ASSIGNED = 'TASK_ASSIGNED',
  TASK_COMPLETED = 'TASK_COMPLETED',

  PERFORMANCE_WARNING = 'PERFORMANCE_WARNING',
  LEAVE_REQUEST = 'LEAVE_REQUEST',
  LEAVE_DECISION = 'LEAVE_DECISION',

  PAYMENT_RECEIVED = 'PAYMENT_RECEIVED',

  USER_CREATED = 'USER_CREATED',
  PASSWORD_RESET = 'PASSWORD_RESET',

  ADMIN_BROADCAST = 'ADMIN_BROADCAST',
  SYSTEM_ALERT = 'SYSTEM_ALERT',
}
